export default {
  products: [
    {
      _id: '1',
      name: 'full shirt',
      category: 'Shirts',
      image: '/images/product-1.jpg',
      price: 60,
      brand: 'nike',
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'amazing shirt',
      category: 'Shirts',
      image: '/images/product-2.jpg',
      price: 60,
      brand: 'adidas',
      rating: 3,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: '3',
      name: 'torrific shirt',
      category: 'Shirts',
      image: '/images/product-3.jpg',
      price: 60,
      brand: 'mango',
      rating: 3,
      numReviews: 198,
      countInStock: 0,
    },
    {
      _id: '4',
      name: 'amazing pants',
      category: 'Pants',
      image: '/images/product-4.jpg',
      price: 60,
      brand: 'adidas',
      rating: 3,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'terrible pants',
      category: 'Pants',
      image: '/images/product-5.jpg',
      price: 60,
      brand: 'levis',
      rating: 3,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: '6',
      name: 'wonderful pants',
      category: 'Pants',
      image: '/images/product-6.jpg',
      price: 60,
      brand: 'zara',
      rating: 3,
      numReviews: 198,
      countInStock: 6,
    },
  ],
};
